seed: 42
evaluation_strategy: cv5_test20   # hoặc holdout70_10_20
class_imbalance: balanced         # 'balanced' hoặc 'smote' (nếu triển khai)
profit:
  profit_per_tp: 100.0            # P: lợi nhuận khi gọi đúng
  call_cost: 2.0                  # C: chi phí mỗi cuộc gọi
features:
  use_duration: false             # tránh leakage khi triển khai
  groups:
    personal: [age, job, marital, education, default, housing, loan]
    contact_campaign: [contact, month, day_of_week, duration, campaign]
    frequency: [pdays, previous, poutcome]
    macro: [emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed]
target: y
